### PR TITLE
chore(links): Fix broken service links

### PR DESCRIPTION
**Pull request by ajwild**
More of the same link fixes as in PR #347, but for the service branch this time. I couldn't fix as many links as I managed in the other PR as there seems to be some missing documentation regarding Elasticsearch indexing, webhooks, and metadata.

### CODE REVIEW

**Comment by gabrielhase** [comment]
The documentation is actually not missing, it's just that the service gives you much less possibilities, e.g. you will not have the possibility to ever interact with ES through the service, so documenting our ES setup would only be confusing for service consumers.

**Review by gabrielhase — APPROVED** [review]
👍

**Comment by ajwild** [comment]
> The documentation is actually not missing, it's just that the service gives you much less possibilities, e.g. you will not have the possibility to ever interact with ES through the service, so documenting our ES setup would only be confusing for service consumers.

@gabrielhase does it mean that this section should be removed:
https://developers.livingdocs.io/reference-docs/project-config/content_types#public-api-config

**Comment by gabrielhase** [comment]
> @gabrielhase does it mean that this section should be removed:
https://developers.livingdocs.io/reference-docs/project-config/content_types#public-api-config

I don't know, the link is a deadlink 😆 
If the publication index can be configured via the project-config it should be in the service docs. If it's only possible with code or instance config, then not.

**Pull request merged**
